name: 💡 General Feature Request
description: Have a new idea/feature for this project? Please suggest!
title: '[FEATURE] Description'
labels: ['feat']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the enhancement you propose, also include what you tried and what worked.
    validations:name: 💡 Feature Request
description: Suggest a new idea or improvement for the Weather Dashboard project
title: "[FEATURE]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! 🚀  
        Please provide as much detail as possible so we can understand and evaluate your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
      placeholder: "I find it difficult to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you would like to see implemented.
      placeholder: "It would be great if the app could..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: "I also thought about..."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here.
      placeholder: "Screenshots, links, or examples..."
    v

      required: true
